image:
  file: .gitpod.dockerfile
tasks:
  - name: Install core dependancy
    init: |
      pip install -U pip
      pip install -r core/requirements/dev.txt
      export ENV=dev
  - name: Start Mongodb
    init: |
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data
  - name: Run Webapp
    init: |
      cd Webapp
      npm install 
      npm run dev
ports:
  - port: 5000
    visibility: public
  - port: 8000
    visibility: public

