version: "3.9"

services:
  api:
    build:
      dockerfile: ./core
    ports:
      - "8080:8000"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data: /etc/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:example}

volumes:
  mongo-data: