version: "3.9"

services:
  api:
    build:
      context: ./core
    ports:
      - "8080:8000"
    environment:
      APP_NAME: ${APP_NAME}
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: db
      MONGO_PORT: 27017
    networks:
      - public
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/etc/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - public


volumes:
  mongo-data:

networks:
  public: